# push:
# branches: [ "main" ]
# pull_request:
# branches: [ "main" ]
workflow_dispatch:
jobs:
build:
runs-on: ubuntu-latest
steps:
- name: Checkout $GITHUB_WORKSPACE
uses: actions/checkout@v3
- name: Setup Python
uses: actions/setup-python@v4.0.0
with:
cache: pip
python-version: '3.7'
- name: Install Dependencies
run: pip install -r requirements.txt
run: jupyter-nbconvert --execute plot_iris_exercise.ipynb --to html
- name: Upload a Build Artifact 
uses: actions/upload-artifact@v3.1.0
with:
name: Artifact
path: plot_iris_exercise.html
